export const products = [
  {
    title:
      "Фен Dyson Supersonic HD07 синий медный с 5 насадками в чехле и расческамия",
    category: "dyson стайлер для длинных волос",
    image: "offers-1-img",
    price: 59990,
    oldPrice: 69990,
    discount: "-15%",
    rating: 4.9,
    date: 6,
    popularity: 98,
  },
  {
    title: "Фен Dyson Supersonic HD07 с 5 насадками и подставкой",
    category: "dyson стайлер красный",
    image: "offers-2-img",
    price: 47990,
    oldPrice: 51990,
    discount: "-15%",
    rating: 4.8,
    date: 5,
    popularity: 94,
  },
  {
    title:
      "Фен Dyson Supersonic 4 насадки HD03 с чехлом для хранения цвет сирень",
    category: "dyson hs01 airwrap compliete",
    image: "offers-3-img",
    price: 46990,
    oldPrice: 51990,
    discount: "-15%",
    rating: 4.7,
    date: 4,
    popularity: 88,
  },
  {
    title: "Фен-щетка Dyson Airwrap Complete Long с набором насадок",
    category: "фен щетка дайсон",
    image: "offers-1-img",
    price: 62990,
    oldPrice: 71990,
    discount: "-13%",
    rating: 4.9,
    date: 3,
    popularity: 91,
  },
  {
    title: "Стайлер Dyson Airwrap HS05 Complete Long медный никель",
    category: "dyson стайлер для длинных волос",
    image: "offers-2-img",
    price: 57990,
    oldPrice: 64990,
    discount: "-11%",
    rating: 4.6,
    date: 10,
    popularity: 84,
  },
  {
    title: "Стайлер Dyson Airwrap красный с дорожным чехлом",
    category: "dyson стайлер красный",
    image: "offers-3-img",
    price: 54990,
    oldPrice: 59990,
    discount: "-8%",
    rating: 4.5,
    date: 9,
    popularity: 82,
  },
  {
    title: "Dyson HS01 Airwrap Complete для укладки и сушки волос",
    category: "dyson hs01 airwrap compliete",
    image: "offers-1-img",
    price: 43990,
    oldPrice: 48990,
    discount: "-10%",
    rating: 4.4,
    date: 8,
    popularity: 76,
  },
  {
    title: "Фен-щетка Dyson с круглыми насадками и кейсом",
    category: "фен щетка дайсон",
    image: "offers-2-img",
    price: 39990,
    oldPrice: 45990,
    discount: "-13%",
    rating: 4.3,
    date: 7,
    popularity: 72,
  },
  {
    title: "Фен-щетка Dyson с круглыми насадками и кейсом",
    category: "фен щетка дайсон",
    image: "offers-2-img",
    price: 39990,
    oldPrice: 45990,
    discount: "-13%",
    rating: 4.3,
    date: 7,
    popularity: 72,
  },
  {
    title: "Фен-щетка Dyson с круглыми насадками и кейсом",
    category: "Test",
    image: "offers-2-img",
    price: 39990,
    oldPrice: 45990,
    discount: "-13%",
    rating: 4.3,
    date: 7,
    popularity: 72,
  },
  {
    title: "Фен-щетка Dyson с круглыми насадками и кейсом",
    category: "Test2",
    image: "offers-2-img",
    price: 39990,
    oldPrice: 45990,
    discount: "-13%",
    rating: 4.3,
    date: 7,
    popularity: 72,
  },
  {
    title: "Фен-щетка Dyson с круглыми насадками и кейсом",
    category: "Test3",
    image: "offers-2-img",
    price: 39990,
    oldPrice: 45990,
    discount: "-13%",
    rating: 4.3,
    date: 7,
    popularity: 72,
  },
];